# -*- coding: utf-8 -*-
"""Assignment_Web_Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qz1rQvJwqIHBaPaHkd1m_pdW8NOgOcBG
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://quotes.toscrape.com/'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

quotes = soup.find_all('div', class_='quote')

#quotes = soup.select('div', class_='quote')

#for quote in quotes:
 # print(quote.text)
quotes

results = []
for item in quotes:
  data = dict()

  #data collection
  data['quote'] = item.select_one('.text').text
  data['url'] = item.select_one('.tags a').get('href')

  results.append(data)

pd.DataFrame(results)